#ifndef PROBLEM2_H_
#define PROBLEM2_H_

// Even Fibonacci numbers
// 
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 
//			1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//	
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
//
class Problem2
{
public:
	Problem2();
	~Problem2();

	const int SEQ_MAX_VALUE = 4000000;
	int Solve();
private:
	int fibo(int n);
};
#endif  // PROBLEM2_H_
